// Makes `Tools` the catalog a tool is chosen from (issue #507), and reports the catalog.
//
// WHAT CHANGES. A tool was a name somebody typed on the registration form, found or created
// as they submitted (#338). Since #507 the office keeps the catalog here instead: a row is
// one kind of tool, named by its path — `Level 1` the category, `Level 2` the tool, `Size`
// the size — and carrying a `Class`, and a registration picks a row. `Tool Name` stays the
// primary field and becomes a formula, `{Level 2} {Size}`, so every screen that names a kind
// keeps reading the field it read. lib/toolCatalog.js holds the fields, the class's two
// values and the expression, and this script imports them rather than spelling them.
//
// TWO PHASES, WITH ONE HAND STEP BETWEEN THEM, AND THE STEP IS FORCED. A field's TYPE cannot
// be PATCHed through the Metadata API (422) and a formula field cannot be created through it
// (docs/notes/airtable-access.md), but an existing formula's `options.formula` PATCHes
// cleanly. So the first run adds the four fields and copies each row's typed name into
// `Level 2`; Soo converts `Tool Name` to a formula in the Airtable UI with any expression at
// all; and the second run PATCHes the real one, writes the descriptions and checks.
//
// THE COPY IS WHAT MAKES THE CONVERSION LOSE NOTHING. Converting a text field to a formula
// replaces every value it held, and a kind's typed name was its only record. Each row's name
// is copied into `Level 2` before the conversion, where it stays the tool's own word, and the
// hand step is not printed while any row with a name still has an empty `Level 2`.
//
// RE-RUN IT AFTER THE CATALOG IS FILLED, AND IT IS THE CATALOG'S CHECK. Once the schema
// matches, a run writes nothing and reads every row back: it compares each name the base
// computed with lib/toolCatalog.js's rule, and it lists every row a registration cannot
// choose — a level or the class missing, or a path another row already names — which is how
// a row the office typed and the app does not offer gets found.
//
// IT TALKS TO THE REST API DIRECTLY, for create_material_categories_354.mjs' reason: the
// schema half has no SDK. lib/airtableOps.js cannot see these calls, so the run counts them.
//
// Usage (from the repo root):
//   node --env-file=.env.local scripts/import/create_tool_catalog_507.mjs --dry-run
//   node --env-file=.env.local scripts/import/create_tool_catalog_507.mjs
//
// No loader flag: this file and lib/toolCatalog.js import only built-ins and files whose
// extension they spell.
//
// Airtable PAT scopes: schema.bases:read, schema.bases:write, data.records:read,
// data.records:write.
//
// Exit codes, per docs/notes/verification.md: 0 the base matches the spec, 1 something
// failed, 2 nothing failed but something is incomplete (a dry run, or the hand step).

import {
    TOOL_CATALOG_FIELDS,
    TOOL_CLASS_VALUES,
    TOOL_NAME_FORMULA,
    composeToolName,
    readCatalog,
} from "../../lib/toolCatalog.js";

const API_ROOT = "https://api.airtable.com/v0";
const META_ROOT = `${API_ROOT}/meta`;

const TABLE_NAME = "Tools";
const NAME_FIELD = "Tool Name";

/** Airtable's own ceiling on one record-write request. */
const RECORDS_PER_REQUEST = 10;

/**
 * The colors walk Airtable's light palette in declaration order — the rule
 * create_tools_334.py states for the tools axis's two other selects — and the class has no
 * terminal value to give gray.
 */
const CLASS_COLORS = ["blueLight2", "cyanLight2"];

const TABLE_DESCRIPTION =
    "The catalog of tools (#507): one row per kind, named by its path — Level 1 the category, Level 2 the " +
    "tool, Size the size — and carrying a Class. The office fills it here, and the app never writes a row of " +
    "it: a registration picks a row and writes tool items under it. One path is one kind; two rows naming one " +
    "path are one choice, and only the first is offered (lib/toolCatalog.js). A brand or a model, when it " +
    "matters, goes in Level 2. Tool Items holds the physical tools, one row each.";

const NAME_DESCRIPTION =
    "The kind's name, {Level 2} {Size}, and the name every screen says (#507). A formula since #507 — it was " +
    "typed on the registration form from #338, and the app no longer creates a kind. Its expression is " +
    "generated by lib/toolCatalog.js and PATCHed by scripts/import/create_tool_catalog_507.mjs; edit it there.";

/** The four fields, as the base should hold them once this has run. */
const FIELDS = [
    {
        name: TOOL_CATALOG_FIELDS.level1,
        type: "singleLineText",
        description:
            "The category, the catalog's first level (#507), said Category on screen. A registration filters " +
            "the tools by it.",
    },
    {
        name: TOOL_CATALOG_FIELDS.level2,
        type: "singleLineText",
        description:
            "The tool, the catalog's second level (#507), said Tool on screen, and the first half of Tool Name. " +
            "A brand or a model, when two kinds would otherwise share a path, goes here. A level the catalog " +
            "grows goes between this and Size, as a field inserted then.",
    },
    {
        name: TOOL_CATALOG_FIELDS.size,
        type: "singleLineText",
        description:
            "The size, the catalog's last level (#507), and the second half of Tool Name. It stays last when a " +
            "level is inserted before it.",
    },
    {
        name: TOOL_CATALOG_FIELDS.toolClass,
        type: "singleSelect",
        options: { choices: TOOL_CLASS_VALUES.map((name, i) => ({ name, color: CLASS_COLORS[i] })) },
        description:
            "How much the tool matters (#507): A for one that matters more, usually a dearer one, B otherwise. " +
            "Information only — no act in the app reads it. A row without one is not offered to a registration.",
    },
];

class Airtable {
    constructor(token, baseId) {
        this.baseId = baseId;
        this.headers = { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };
        this.calls = 0;
    }

    async request(method, url, body) {
        this.calls++;
        const response = await fetch(url, {
            method,
            headers: this.headers,
            ...(body === undefined ? {} : { body: JSON.stringify(body) }),
        });
        const text = await response.text();
        if (!response.ok) throw new Error(`${method} ${url.replace(this.baseId, "{base}")} -> ${response.status} ${text}`);
        return text === "" ? null : JSON.parse(text);
    }

    async table() {
        const { tables } = await this.request("GET", `${META_ROOT}/bases/${this.baseId}/tables`);
        return tables.find((t) => t.name === TABLE_NAME) ?? null;
    }

    createField(tableId, field) {
        return this.request("POST", `${META_ROOT}/bases/${this.baseId}/tables/${tableId}/fields`, field);
    }

    patchField(tableId, fieldId, patch) {
        return this.request("PATCH", `${META_ROOT}/bases/${this.baseId}/tables/${tableId}/fields/${fieldId}`, patch);
    }

    patchTable(tableId, patch) {
        return this.request("PATCH", `${META_ROOT}/bases/${this.baseId}/tables/${tableId}`, patch);
    }

    async listRecords(tableId, fields) {
        const out = [];
        let offset;
        do {
            const params = new URLSearchParams({ pageSize: "100" });
            for (const f of fields) params.append("fields[]", f);
            if (offset) params.set("offset", offset);
            const page = await this.request("GET", `${API_ROOT}/${this.baseId}/${tableId}?${params}`);
            out.push(...page.records);
            offset = page.offset;
        } while (offset);
        return out;
    }

    /** No `typecast` on this path: every value is a string into a text field. */
    updateRecords(tableId, records) {
        return this.request("PATCH", `${API_ROOT}/${this.baseId}/${tableId}`, { records });
    }
}

function log(message = "") {
    console.log(message);
}

function finish(air, code, verdict) {
    log("");
    log(`${air.calls} Airtable API call(s). ${verdict}.`);
    return code;
}

/**
 * A formula as the Metadata API returned it, with every field it names by id put back to
 * the field's name. The API renders some formulas with `{fldXXXXXXXXXXXXXX}` and some with
 * `{Field Name}` (docs/notes/airtable-access.md counted 12 and 6 of 18), so a comparison of
 * the raw text would call a correct expression wrong.
 */
function byName(table, formula) {
    const names = new Map(table.fields.map((f) => [f.id, f.name]));
    return String(formula ?? "").replace(/\{(fld[A-Za-z0-9]{14})\}/g, (whole, id) => (names.has(id) ? `{${names.get(id)}}` : whole));
}

/** A row in the shape lib/toolCatalog.js reads, from a REST record. */
function toolOf(record) {
    const f = record.fields;
    return {
        id: record.id,
        toolName: f[NAME_FIELD] ?? "",
        level1: f[TOOL_CATALOG_FIELDS.level1] ?? "",
        level2: f[TOOL_CATALOG_FIELDS.level2] ?? "",
        size: f[TOOL_CATALOG_FIELDS.size] ?? "",
        toolClass: f[TOOL_CATALOG_FIELDS.toolClass] ?? "",
    };
}

async function main() {
    const dryRun = process.argv.includes("--dry-run");
    const token = process.env.AIRTABLE_API_KEY;
    const baseId = process.env.AIRTABLE_BASE_ID;
    if (!token || !baseId) {
        log("AIRTABLE_API_KEY and AIRTABLE_BASE_ID must be set — run with --env-file=.env.local");
        return 1;
    }

    const air = new Airtable(token, baseId);
    log(`create_tool_catalog_507 — base ${baseId}${dryRun ? "  (DRY RUN — nothing is written)" : ""}\n`);

    let table = await air.table();
    if (!table) {
        log(`no table named ${TABLE_NAME}; scripts/import/create_tools_334.py creates it.`);
        return finish(air, 1, "nothing to make a catalog of");
    }
    const nameField = table.fields.find((f) => f.name === NAME_FIELD);
    if (!nameField || nameField.id !== table.primaryFieldId) {
        log(`${TABLE_NAME}."${NAME_FIELD}" is not the primary field — stopping.`);
        return finish(air, 1, "the table is not the shape this expects");
    }

    // --- the four fields --------------------------------------------------
    log("the catalog's fields:");
    for (const spec of FIELDS) {
        const live = table.fields.find((f) => f.name === spec.name);
        if (live && live.type !== spec.type) {
            log(`  ${spec.name} exists as a ${live.type}, not the ${spec.type} this needs; a type cannot be PATCHed.`);
            return finish(air, 1, "a field is in the way");
        }
        if (live) {
            log(`  [SKIP]   ${spec.name} (${live.id}) is a ${live.type}`);
        } else if (dryRun) {
            log(`  [WOULD]  create ${spec.name} as a ${spec.type}${spec.options ? ` ${JSON.stringify(spec.options)}` : ""}`);
        } else {
            const made = await air.createField(table.id, spec);
            log(`  [CREATE] ${spec.name} (${made.id}) as a ${made.type}`);
        }
    }
    if (!dryRun) table = await air.table();

    // --- the hand step, and the copy that makes it lose nothing -----------
    if (nameField.type !== "formula") {
        // A dry run on a base without the field reads the names alone: a field the read
        // names and the base lacks is a 422, and every row's `Level 2` is empty then anyway.
        const hasLevel2 = table.fields.some((f) => f.name === TOOL_CATALOG_FIELDS.level2);
        const rows = await air.listRecords(table.id, hasLevel2 ? [NAME_FIELD, TOOL_CATALOG_FIELDS.level2] : [NAME_FIELD]);
        const toCopy = rows.filter((r) => (r.fields[NAME_FIELD] ?? "").trim() !== "" && (r.fields[TOOL_CATALOG_FIELDS.level2] ?? "").trim() === "");
        log(`\n${NAME_FIELD} is still \`${nameField.type}\`: ${rows.length} row(s), ${toCopy.length} whose name is not yet in ${TOOL_CATALOG_FIELDS.level2}.`);
        for (let i = 0; i < toCopy.length; i += RECORDS_PER_REQUEST) {
            const chunk = toCopy.slice(i, i + RECORDS_PER_REQUEST);
            for (const r of chunk) log(`  ${dryRun ? "[WOULD]" : "[COPY]  "} ${r.id}  ${JSON.stringify(r.fields[NAME_FIELD])} into ${TOOL_CATALOG_FIELDS.level2}`);
            if (!dryRun) {
                await air.updateRecords(
                    table.id,
                    chunk.map((r) => ({ id: r.id, fields: { [TOOL_CATALOG_FIELDS.level2]: r.fields[NAME_FIELD] } }))
                );
            }
        }
        if (dryRun) return finish(air, 2, "dry run — nothing was written");

        const after = await air.listRecords(table.id, [NAME_FIELD, TOOL_CATALOG_FIELDS.level2]);
        const uncopied = after.filter((r) => (r.fields[NAME_FIELD] ?? "").trim() !== "" && r.fields[TOOL_CATALOG_FIELDS.level2] !== r.fields[NAME_FIELD]);
        if (uncopied.length > 0) {
            log(`\n${uncopied.length} row(s) hold a name ${TOOL_CATALOG_FIELDS.level2} does not, so the hand step would lose it:`);
            for (const r of uncopied) log(`  ${r.id}  ${JSON.stringify(r.fields[NAME_FIELD])} / ${JSON.stringify(r.fields[TOOL_CATALOG_FIELDS.level2] ?? "")}`);
            return finish(air, 1, "not safe to convert yet");
        }
        log(`  every name is in ${TOOL_CATALOG_FIELDS.level2}, as typed.`);
        return handStep(air);
    }

    // --- the formula and the words ------------------------------------------
    log(`\n${NAME_FIELD} is a formula.`);
    if (byName(table, nameField.options?.formula) === TOOL_NAME_FORMULA) {
        log(`  its expression is already ${TOOL_NAME_FORMULA}`);
    } else if (dryRun) {
        log(`  [WOULD]  PATCH its expression to ${TOOL_NAME_FORMULA}`);
    } else {
        await air.patchField(table.id, nameField.id, { options: { formula: TOOL_NAME_FORMULA } });
        log(`  [PATCH]  its expression is ${TOOL_NAME_FORMULA}`);
    }

    // Descriptions are synced, not only set on create: the base's copy is the one somebody
    // reads while typing into the cell (create_material_categories_354.mjs has the reason).
    const wantDescriptions = [[NAME_FIELD, NAME_DESCRIPTION], ...FIELDS.map((f) => [f.name, f.description])];
    for (const [name, description] of wantDescriptions) {
        const live = table.fields.find((f) => f.name === name);
        if (!live || (live.description ?? "") === description) continue;
        if (dryRun) {
            log(`  [WOULD]  update ${name}'s description`);
            continue;
        }
        await air.patchField(table.id, live.id, { description });
        log(`  [PATCH]  ${name}'s description`);
    }
    if ((table.description ?? "") !== TABLE_DESCRIPTION) {
        if (dryRun) log(`  [WOULD]  update the table's description`);
        else {
            await air.patchTable(table.id, { description: TABLE_DESCRIPTION });
            log(`  [PATCH]  the table's description`);
        }
    }
    if (dryRun) return finish(air, 2, "dry run — nothing was written");

    // --- verification is part of the run ----------------------------------
    log(`\nverifying against the live base:`);
    table = await air.table();
    const failures = [];
    const field = (name) => table.fields.find((f) => f.name === name);
    if (field(NAME_FIELD)?.type !== "formula") failures.push(`${NAME_FIELD} is ${field(NAME_FIELD)?.type}, not a formula`);
    if (byName(table, field(NAME_FIELD)?.options?.formula) !== TOOL_NAME_FORMULA) {
        failures.push(`${NAME_FIELD}'s expression is ${JSON.stringify(byName(table, field(NAME_FIELD)?.options?.formula))}`);
    }
    for (const spec of FIELDS) {
        const live = field(spec.name);
        if (!live) failures.push(`${spec.name} is missing`);
        else if (live.type !== spec.type) failures.push(`${spec.name} is ${live.type}, not ${spec.type}`);
    }
    const choices = (field(TOOL_CATALOG_FIELDS.toolClass)?.options?.choices ?? []).map((c) => `${c.name}/${c.color}`);
    const wantChoices = TOOL_CLASS_VALUES.map((name, i) => `${name}/${CLASS_COLORS[i]}`);
    if (choices.join(" | ") !== wantChoices.join(" | ")) failures.push(`Class's choices are ${choices.join(" | ")}, not ${wantChoices.join(" | ")}`);

    const records = await air.listRecords(table.id, [
        NAME_FIELD,
        TOOL_CATALOG_FIELDS.level1,
        TOOL_CATALOG_FIELDS.level2,
        TOOL_CATALOG_FIELDS.size,
        TOOL_CATALOG_FIELDS.toolClass,
    ]);
    const tools = records.map(toolOf);
    for (const tool of tools) {
        const expected = composeToolName(tool);
        if (tool.toolName !== expected) {
            failures.push(`${tool.id}: the base named it ${JSON.stringify(tool.toolName)}, the rule names it ${JSON.stringify(expected)}`);
        }
    }

    const { offered, setAside } = readCatalog(tools);
    log(`  ${tools.length} row(s); ${offered.length} a registration may pick.`);
    if (setAside.length > 0) {
        log(`  ${setAside.length} row(s) a registration cannot pick, for the office to fill or remove:`);
        for (const { tool, reason, missing, of } of setAside) {
            const why = reason === "incomplete" ? `missing ${missing.map((m) => TOOL_CATALOG_FIELDS[m]).join(", ")}` : `the path ${of.id} already names`;
            log(`    ${tool.id}  ${JSON.stringify(tool.toolName)} — ${why}`);
        }
    }

    if (failures.length > 0) {
        log(`  ${failures.length} problem(s):`);
        for (const line of failures) log(`    ${line}`);
        return finish(air, 1, "the base does not match the spec");
    }
    log(`  the fields, the class's choices, the expression and every name match.`);
    return finish(air, 0, "the base matches the spec");
}

/** The one step the API cannot take, printed where it cannot be lost. */
function handStep(air) {
    log("");
    log("=".repeat(72));
    log("HAND STEP — in the Airtable UI, then run this again:");
    log("");
    log(`  Open ${TABLE_NAME} and change ${NAME_FIELD}'s type from "Single line text"`);
    log(`  to "Formula". The expression does not matter — put anything in, or leave`);
    log(`  the editor's default. The next run PATCHes the real one.`);
    log("");
    log("  Why by hand: a field's type cannot be PATCHed through the Metadata API,");
    log("  and a formula field cannot be created through it; an existing formula's");
    log("  expression can be PATCHed, which is what the next run does.");
    log("=".repeat(72));
    return finish(air, 2, "waiting on the hand step above");
}

main().then(
    (code) => process.exit(code),
    (error) => {
        console.error(`\nfailed: ${error.message}`);
        process.exit(1);
    }
);
